name: fedscale
channels:
  - pytorch
  - conda-forge
  - anaconda
  - defaults
  - gurobi
dependencies:
  - python=3.7
  - gurobi=9.1.0
  - tensorboard
  - numba=0.49.1
  - librosa=0.7.2
  - pip=20.0.2
  - pip:
    - torch_optimizer
    - torch
    - tensorflow
    - torchvision
    - transformers
    - scipy==1.4.1
    - matplotlib==3.1.3
    - torch_baidu_ctc==0.3.0
    - tensorboardX==2.1
    - python-levenshtein==0.12.0
    - pandas==1.1.0
    - PyYAML
    - sox==1.3.7
    - grpcio==1.40.0
    - gym
    - jupyter
    - opacus
    - pillow==9
    - sentencepiece
    - gdown
    - h5py
